### ISSUE TITLE
Negative node ids?

### ISSUE THREAD

**Issue by ekiwi** [Boolector/btor2tools#12]
I encountered a btor file in your examples that contains a negative node id: https://github.com/Boolector/btor2tools/blob/6ba194b3d58774b5d13e92b198367dedd5b80236/examples/btorsim/twocount2.btor2#L13

Looking at the [spec](https://link.springer.com/content/pdf/10.1007%2F978-3-319-96145-3_32.pdf) it isn't clear to me what a negative node id means. According to the grammar `(nid) := (num)` and `num` is defined as a positive unsigned integer.

I would appreciate any explanation what the meaning of a negative node id is. Thanks!

**Comment by ekiwi** [comment]
I had another look at the Btor2 paper and discovered that the example in `Fig 3` also has a negative node id.
Do I interpret this correctly as inverting a boolean (i.e. 1-bit bitvector)? Can this be used anywhere a 1-bit signal is used? What happens if a multi-bit signal is refereed to with a negative node id? Do all bits get inverted?

**Comment by mpreiner** [comment]
A negative node id is a shorthand for bitwise negation, which can be used for any Boolean or bit-vector term.

**Comment by ekiwi** [comment]
> A negative node id is a shorthand for bitwise negation, which can be used for any Boolean or bit-vector term.

Thanks for the confirmation!

I fixed it in my implementation: https://github.com/ucb-bar/maltese-smt/commit/c953052c6b9a70f705e74e48546966a58c75a11f
