### ISSUE TITLE
Parse error for `init`: state id must be greater than id of second operand

### ISSUE THREAD

**Issue by nianzelee** [Boolector/btor2tools#14]
Hi,

I am trying to understand the BTOR2 format.
I ran `catbtor` (built at b8456dd) with the BTOR2 model `program.btor2` of the example program in the CAV 2018 paper.

```
1 sort bitvec 1
2 sort bitvec 32
3 input 1 turn
4 state 2 a
5 state 2 b
6 zero 2
7 init 2 4 6
8 init 2 5 6
9 one 2
10 add 2 4 9
11 add 2 5 9
12 ite 2 3 4 10
13 ite 2 -3 5 11
14 next 2 4 12
15 next 2 5 13
16 constd 2 3
17 eq 1 4 16
18 eq 1 5 16
19 and 1 17 18
20 bad 19
```

However, I received a parse error:

```
*** catbtor: parse error in 'program.btor2' line 7: state id must be greater than id of second operand
```

Is this an intended behavior of the parser?
I could not find information on such restrictions in the CAV paper.
(The file can be successfully parsed if the line `6 zero 2` gets an `nid` smaller than a's and b's.)

Thanks!

**Comment by mpreiner** [comment]
Yes, this is intended behavior. This restriction was introduced after the CAV paper to simplify cycle checks for state initialization.

**Comment by nianzelee** [comment]
Thank you for the explanation!
