### ISSUE TITLE
Negating an array with the minus sign

### ISSUE THREAD

**Issue by nianzelee** [Boolector/btor2tools#16]
Consider the following BTOR2 file:

```
1 sort bitvec 3
2 sort bitvec 24
3 sort array 1 2
4 state 3
5 input 1
6 read 2 -4 5
```

Although line 6 negates an array with `-` (which should be invalid),  `catbtor` does not complain about it.

However, if `7 not 3 4` is appended to the file, `catbtor` reports:

```
*** catbtor: parse error in 'array_not.btor2' line 7: expected bitvec sort for not
```

It would be better if `catbtor` could detect the error of the negated array at line 6.

**Comment by mpreiner** [comment]
That's a good point, - is only valid shorthand for bit-vectors. We'll fix this.
