### ISSUE TITLE
Partial register initialization

### ISSUE THREAD

**Issue by Po-Chun-Chien** [Boolector/btor2tools#21]
In Btor2, both registers (states of bit-vector sort) and memories (states of array sort)
are initialized randomly unless `init` is used to explicitly initialize their values.
The allows the partial initialization of a register by
applying a bit-mask to an uninitialized register.

For example, consider the Btor2 circuit:

```
1 sort bitvec 3
2 const 1 001
3 state 1
4 const 1 100
5 and 1 3 4
6 state 1
7 init 1 6 5
```

The register at line 6 is initialized to `?00` (`?` indicates a random Boolean value).

If we append the following line to initialize the register at line 3:

```
8 init 1 3 2
```

What will the register at line 6 be initialized to in this case?
Will it now become `000` (`001` & `100`) or remain as `?00`?

**Comment by Po-Chun-Chien** [comment]
I wanted to write a small Btor2 example and test it with BtorMC (downloaded from <https://fmv.jku.at/cav18-btor2/>),
but BtorMC failed with the following error:

```
line 7: expected id of constant as second argument
```

**Comment by mpreiner** [comment]
Partial initialization should be supported. The newest version of btormc from https://github.com/Boolector/boolector does not complain about this.

**Comment by Po-Chun-Chien** [comment]
I tested the following Btor2 circuit using BtorMC (6603ed7):

```
1 sort bitvec 3
2 const 1 001
3 state 1
4 const 1 100
5 and 1 3 4
6 state 1
7 init 1 6 5
8 init 1 3 2 ; comment out to enable partial initialization
9 sort bitvec 1
10 const 1 000
11 neq 9 6 10
12 bad 11 ; state_6 != 000
13 next 1 3 3
14 next 1 6 6
```

The results are:
- unsat w/ line 8
- sat w/o line 8

Therefore, the register at line 6 is initialized to `000`.
