### ISSUE TITLE
btorsim: `BTOR2_tag_iff` not marked as implemented

### ISSUE THREAD

**Issue by Ferdi265** [Boolector/btor2tools#22]
Btorsim is missing an implementation of the `iff` operation.

**Comment by mpreiner** [comment]
This should be handled in https://github.com/Boolector/btor2tools/blob/master/src/btorsim/btorsim.cpp#L696, do you have a specific input where btorsim fails?

**Comment by Ferdi265** [comment]
Testcase:

```
;; -----------------------------------------------------------------------------
;; manually written btor file for testing binary operators
;; -----------------------------------------------------------------------------
1 sort bitvec 1
2 sort bitvec 8
;; -----------------------------------------------------------------------------
;; iff true true
;; -----------------------------------------------------------------------------
3 one 1
4 one 1
5 iff 1 3 4
6 bad 5 iff-true-true
```

(this should reach the `bad` state, but fails with current btorsim)

**Comment by Ferdi265** [comment]
> This should be handled in https://github.com/Boolector/btor2tools/blob/master/src/btorsim/btorsim.cpp#L696, do you have a specific input where btorsim fails?

Ahh, I just noticed that fallthrough. You're correct, the implementation was already there, but the big switch-case printing the `"unsupported '%"PRId64"' %s"` error message was missing an entry for `iff`. I'll remove the redundant implementation from my PR.
