### ISSUE TITLE
Build with btor2aiger fails

### ISSUE THREAD

**Issue by lonsing** [Boolector/btor2tools#5]
The following commands to build with btor2aiger produce an error (Ubuntu 18.04.4, commit 9831f9909fb283752a3d6d60d43613173bd8af42):

```
git clone https://github.com/Boolector/btor2tools.git
cd btor2tools/
./setup-deps.sh
```

Error: `*** configure.sh: invalid option '-fPIC' (try '-h')`

The error occurs when running script `deps/boolector/contrib/setup-btor2tools.sh`, which is called in `./setup-deps.sh`.

The patch below fixes the above error, but the installation flow still fails as follows:

`cp: cannot stat 'build/libbtor2parser.a': No such file or directory`

```

diff --git a/setup-deps.sh b/setup-deps.sh
index 4450d4c..b661a5c 100755
--- a/setup-deps.sh
+++ b/setup-deps.sh
@@ -18,6 +18,8 @@ git clone https://github.com/boolector/boolector deps/boolector
 cd deps/boolector
 git checkout bitblast-api
 
+sed "s/-fPIC//g" -i ./contrib/setup-btor2tools.sh
+sed "/configure/a cd build" -i ./contrib/setup-btor2tools.sh
 ./contrib/setup-btor2tools.sh
 ./contrib/setup-lingeling.sh
 ./configure.sh --prefix $(pwd)/../install
```

**Comment by andrewvaughanj** [comment]
Some quick points:

1. Can you post the whole output of running setup-btor2tools.sh?

2. Can you provide the output of `which gcc` and/or `which $CC`?

3. Can you provide the output of `gcc -dumpversion` and/or `$CC -dumpversion`? If this gives a single number, can you provide `gcc --version`?

4. Does this happen on `master`? The `bitblast-api` branch is 341 commits behind `master`; while `rebase origin/master` does have conflicts, they're trivial to fix, so maybe that's worth a shot?

**Comment by lonsing** [comment]
I created a pull request in boolector which fixes the problem: https://github.com/Boolector/boolector/pull/132

The `./setup-deps.sh` script clones boolector and checks out the `bitblast-api` branch. The above pull request fixes some setup scripts on `bitblast-api`, which were outdated compared to boolector's master branch.

**Comment by mpreiner** [comment]
I rebased the bitblast-api branch on master, which should fix your issues.
